//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int Document_ID { get; set; }
        public string Document_Name { get; set; }
        public string Document_Description { get; set; }
        public Nullable<int> Document_RubricID { get; set; }
        public string Document_CreationDate { get; set; }
        public string Document_Address { get; set; }
    
        public virtual Rubrics Rubrics { get; set; }
    }
}
